package grant_all_test

import (
	"errors"
	"github.com/attestify/go-kernel/access_control"
	"github.com/attestify/go-kernel/access_control/grant_all"
	"github.com/attestify/go-kernel/access_control/permission"
	"github.com/attestify/go-kernel/error/internal_error"
	"testing"
)

func setup(t *testing.T) {
	t.Parallel()
}

/** Happy Path **/

func Test_Instantiate_GrantAll_Successfully(t *testing.T) {
	setup(t)

	// Assemble
	var gateway = NewMockGrantAllGateway()

	// Act
	usecase := grant_all.New(&gateway)

	// Assert
	if usecase.HasError() {
		t.Errorf("Encountered an unexpected error.\n Error: %s\n", usecase.Error())
	}
}

func Test_Invoke_Grant_Successfully(t *testing.T) {
	setup(t)

	// Assemble
	var gateway = NewMockGrantAllGateway()
	var resourceId int64 = 1
	var permissions = []string{permission.Read}

	// Act
	usecase := grant_all.New(&gateway)
	usecase.Grant(resourceId, permissions)

	// Assert
	if usecase.HasError() {
		t.Errorf("Encountered an unexpected error.\n Error: %s\n", usecase.Error())
	}
}

/** Sad Path **/

func Test_Handle_InternalError_With_Nil_GrantAllGateway_When_Instantiated(t *testing.T) {
	setup(t)

	// Assemble
	var gateway grant_all.GrantAllGateway = nil

	// Act
	usecase := grant_all.New(gateway)

	// Assert
	if usecase.HasError() != true {
		t.Fatal("Expected an error, although none was provided.")
	}

	if !errors.As(usecase.Error(), &internal_error.InternalError{}) {
		t.Errorf("did not get the epected error of type InternalError")
	}

	// This assertion ensure the InternalError is generated from the nil gateway check
	actualMessage := usecase.Error().Error()
	expectedMessage := "The provided GrantAllGateway is nil. Please provide a valid instance of an GrantAllGateway."
	if expectedMessage != actualMessage {
		t.Errorf("The returned error message was not expected: \n Expected: %s \n Actual %s", expectedMessage, actualMessage)
	}
}

func Test_Handle_GrantAllGateway_Returns_InternalError_When_Grant_Invoked(t *testing.T) {
	setup(t)

	// Assemble
	gateway := NewMockGrantAllGateway()
	gateway.GrantAllGatewayInternalError()
	var resourceId int64 = 1
	var permissions = []string{permission.Read}

	// Act
	usecase := grant_all.New(&gateway)
	usecase.Grant(resourceId, permissions)

	// Assert
	if usecase.HasError() != true {
		t.Fatal("Expected an error, although none was provided.")
	}

	if !errors.As(usecase.Error(), &internal_error.InternalError{}) {
		t.Errorf("did not get the epected error of type InternalError")
	}

	// This assertion ensure the InternalError is generate when the GrantAll.Grant(...) method is invoked
	// If the message is other than what's here, the InternalError was generated by something else than .Grant(...)
	// By testing this, we can expect that and InternalError generated  by any other implementation of the
	// GrantAllGateway will be properly handled
	actualMessage := usecase.Error().Error()
	expectedMessage := "Error generated from GrantAll.Grant() invocation."
	if expectedMessage != actualMessage {
		t.Errorf("The returned error message was not expected: \n Expected: %s \n Actual %s", expectedMessage, actualMessage)
	}

}

func Test_Returns_InternalError_With_Nil_GrantAllGateway_When_Grant_Invoked(t *testing.T) {
	setup(t)

	// Assemble
	var gateway grant_all.GrantAllGateway = nil
	var resourceId int64 = 1
	var permissions = []string{permission.Read}

	// Act
	usecase := grant_all.New(gateway)
	usecase.Grant(resourceId, permissions)

	// Assert
	if usecase.HasError() != true {
		t.Fatal("Expected an error, although none was provided.")
	}

	if !errors.As(usecase.Error(), &internal_error.InternalError{}) {
		t.Errorf("did not get the epected error of type InternalError")
	}

	// This assertion ensure the InternalError is generated from the nil gateway check
	actualMessage := usecase.Error().Error()
	expectedMessage := "The provided GrantAllGateway is nil. Please provide a valid instance of an GrantAllGateway."
	if expectedMessage != actualMessage {
		t.Errorf("The returned error message was not expected: \n Expected: %s \n Actual %s", expectedMessage, actualMessage)
	}
}

/** Testing Tools **/

type MockGrantAllGateway struct {
	hasInternalError bool
	mockError        error
}

func NewMockGrantAllGateway() MockGrantAllGateway {
	return MockGrantAllGateway{}
}

func (gateway *MockGrantAllGateway) Grant(control access_control.AccessControl) {
	if gateway.hasInternalError {
		gateway.mockError = internal_error.New("Error generated from GrantAll.Grant() invocation.")
	}
}

func (gateway MockGrantAllGateway) HasError() bool { return gateway.mockError != nil }

func (gateway MockGrantAllGateway) Error() error { return gateway.mockError }

func (gateway *MockGrantAllGateway) GrantAllGatewayInternalError() {
	gateway.hasInternalError = true
}
